import { StyleSheet } from "react-native";
import type { ThemeTokens } from "@leftcar/ui-tokens";

export function createCatalogStyles(colors: ThemeTokens, isDark: boolean) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.bgCanvas,
    },
    root: {
      flex: 1,
      backgroundColor: colors.bgCanvas,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 32,
      gap: 10,
      width: "100%",
      maxWidth: 840,
      alignSelf: "center",
    },
    headerContainer: {
      gap: 10,
      marginBottom: 4,
    },
    hostStrip: {
      backgroundColor: colors.bgSurface,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 9,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    hostStripLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flex: 1,
      minWidth: 0,
    },
    dotConnected: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.statusLive,
      flexShrink: 0,
    },
    hostStripText: {
      color: colors.textSecondary,
      fontSize: 12,
      flex: 1,
    },
    hostStripAddr: {
      color: colors.textPrimary,
      fontWeight: "700",
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
    },
    transportStrip: {
      backgroundColor: colors.bgSurface,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    transportDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.textDim,
    },
    transportDotUsb: {
      backgroundColor: colors.brandPrimary,
    },
    transportText: {
      color: colors.textSecondary,
      fontSize: 13,
      flex: 1,
    },
    transportAction: {
      backgroundColor: colors.btnSecondaryBg,
      borderWidth: 1,
      borderColor: colors.btnSecondaryBorder,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
    },
    transportActionText: {
      color: colors.btnSecondaryText,
      fontSize: 13,
      fontWeight: "600",
    },
    btnHostChange: {
      backgroundColor: colors.btnSecondaryBg,
      borderWidth: 1,
      borderColor: colors.btnSecondaryBorder,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 38,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    btnHostChangeText: {
      color: colors.btnSecondaryText,
      fontSize: 13,
      fontWeight: "600",
    },
    hostStripActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    btnHostSettings: {
      backgroundColor: colors.btnSecondaryBg,
      borderWidth: 1,
      borderColor: colors.btnSecondaryBorder,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 38,
      borderRadius: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
    },
    btnHostSettingsText: {
      color: colors.btnSecondaryText,
      fontSize: 13,
      fontWeight: "600",
    },

    /* Error Card */
    errorCard: {
      backgroundColor: colors.bgSurface,
      borderWidth: 1,
      borderColor: colors.borderStrong,
      borderRadius: 10,
      padding: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    errorText: {
      color: colors.textPrimary,
      fontSize: 13,
      lineHeight: 18,
    },
    errorBody: {
      flex: 1,
      gap: 8,
    },
    errorActions: {
      flexDirection: "row",
      gap: 8,
    },
    errorRetryBtn: {
      backgroundColor: colors.btnPrimaryBg,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 36,
      alignItems: "center",
      justifyContent: "center",
    },
    errorRetryText: {
      color: colors.btnPrimaryText,
      fontSize: 13,
      fontWeight: "600",
    },
    errorHostBtn: {
      backgroundColor: colors.btnSecondaryBg,
      borderWidth: 1,
      borderColor: colors.btnSecondaryBorder,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 36,
      alignItems: "center",
      justifyContent: "center",
    },
    errorHostText: {
      color: colors.btnSecondaryText,
      fontSize: 13,
      fontWeight: "600",
    },

    /* Segmented Quality */
    qualityContainer: {
      gap: 6,
    },
    qualitySegmentWrapper: {
      backgroundColor: colors.bgSurface,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      padding: 3,
    },
    qualitySegmentTabs: {
      flexDirection: "row",
      gap: 3,
    },
    qualityTab: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 4,
      minHeight: 44,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
      backgroundColor: "transparent",
    },
    qualityTabActive: {
      backgroundColor: colors.btnPrimaryBg,
    },
    qualityTabLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    qualityTabLabelActive: {
      color: colors.btnPrimaryText,
      fontWeight: "700",
    },
    qualityTabDetail: {
      fontSize: 12,
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
      color: colors.textSecondary,
    },
    qualityTabDetailActive: {
      color: colors.btnPrimaryText,
      opacity: 0.85,
    },
    qualityHintRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 4,
    },
    qualityHintText: {
      fontSize: 12,
      color: colors.textSecondary,
      lineHeight: 16,
      flex: 1,
    },

    /* Collapsible Advanced Streaming Controls */
    advancedToggleRow: {
      backgroundColor: colors.bgSurface,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    advancedToggleLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    advancedToggleText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    reconnectDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.textPrimary,
    },
    advancedSectionContainer: {
      gap: 10,
      paddingTop: 2,
    },

    /* Section Title */
    sectionTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 2,
      marginTop: 4,
    },
    sectionTitleText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    btnRefresh: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      minHeight: 32,
      justifyContent: "center",
    },
    btnRefreshText: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: "600",
    },
    btnDisabled: {
      opacity: 0.5,
    },

    /* Display Cards */
    displayCard: {
      backgroundColor: colors.bgSurface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      padding: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    displayMain: {
      flex: 1,
      minWidth: 0,
      gap: 4,
    },
    displayNameRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    displayName: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
      flex: 1,
    },
    displayIndexBadge: {
      backgroundColor: colors.bgSubtle,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      borderRadius: 5,
      paddingHorizontal: 6,
      paddingVertical: 2,
    },
    displayIndexText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
      fontFamily: "monospace",
    },
    chipsRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    chip: {
      backgroundColor: colors.bgSubtle,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
    },
    chipText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
    },
    openBtn: {
      backgroundColor: colors.btnPrimaryBg,
      paddingHorizontal: 16,
      paddingVertical: 10,
      minHeight: 44,
      borderRadius: 10,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    openBtnText: {
      color: colors.btnPrimaryText,
      fontSize: 14,
      fontWeight: "700",
    },
    streamingBadge: {
      backgroundColor: colors.statusLiveSubtle,
      borderWidth: 1,
      borderColor: colors.statusLiveBorder,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 40,
      borderRadius: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      flexShrink: 0,
    },
    streamingBadgeText: {
      color: colors.statusLive,
      fontSize: 12,
      fontWeight: "700",
    },
    btnSwitchDisplay: {
      backgroundColor: colors.btnSecondaryBg,
      borderWidth: 1,
      borderColor: colors.btnSecondaryBorder,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 40,
      borderRadius: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
      flexShrink: 0,
    },
    btnSwitchDisplayText: {
      color: colors.btnSecondaryText,
      fontSize: 12,
      fontWeight: "600",
    },

    /* Empty State */
    emptyCard: {
      backgroundColor: colors.bgSurface,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      padding: 24,
      alignItems: "center",
      gap: 8,
    },
    loadingText: {
      color: colors.textSecondary,
      fontSize: 12,
    },
    emptyText: {
      color: colors.textSecondary,
      fontSize: 12,
    },

    /* Active Streams */
    activeSection: {
      marginTop: 8,
      gap: 8,
    },
    activeSectionHeader: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    activeSectionTitle: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    activeCountBadge: {
      backgroundColor: colors.statusLiveSubtle,
      borderWidth: 1,
      borderColor: colors.statusLiveBorder,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
    },
    activeCountText: {
      color: colors.statusLive,
      fontSize: 12,
      fontWeight: "700",
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
    },
    streamCard: {
      backgroundColor: colors.bgSurface,
      borderWidth: 1,
      borderColor: colors.borderCard,
      borderRadius: 10,
      padding: 12,
      gap: 8,
    },
    streamCardTop: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 8,
    },
    streamInfo: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    streamNameRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    dotActive: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.statusLive,
    },
    streamName: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.textPrimary,
      flex: 1,
    },
    sourceTag: {
      backgroundColor: colors.bgSubtle,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    sourceTagText: {
      color: colors.textSecondary,
      fontSize: 12,
      fontFamily: "monospace",
    },
    streamResolution: {
      fontSize: 12,
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
      color: colors.textSecondary,
    },
    streamFps: {
      fontSize: 12,
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
      color: colors.textPrimary,
      fontWeight: "700",
    },
    streamKbps: {
      fontSize: 12,
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
      color: colors.textSecondary,
    },
    streamPort: {
      color: colors.textSecondary,
      fontSize: 12,
      fontFamily: "monospace",
      fontVariant: ["tabular-nums"],
    },
    transportBadge: {
      fontSize: 12,
      fontFamily: "monospace",
      color: colors.textSecondary,
      backgroundColor: colors.bgSubtle,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    streamError: {
      color: colors.textSecondary,
      fontSize: 12,
      overflow: "hidden",
    },
    streamSpecRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    streamActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexShrink: 0,
    },
    btnChangeResolution: {
      backgroundColor: colors.btnSecondaryBg,
      borderWidth: 1,
      borderColor: colors.btnSecondaryBorder,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 38,
      borderRadius: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 4,
    },
    btnChangeResolutionText: {
      color: colors.btnSecondaryText,
      fontSize: 13,
      fontWeight: "600",
    },
    stopBtn: {
      backgroundColor: colors.statusDangerSubtle,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 38,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      flexShrink: 0,
    },
    stopBtnText: {
      color: colors.statusDanger,
      fontSize: 13,
      fontWeight: "600",
    },
    displaySwitchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginTop: 4,
      paddingTop: 6,
      borderTopWidth: 1,
      borderTopColor: colors.borderSubtle,
    },
    displaySwitchLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    displaySwitchChips: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      flexWrap: "wrap",
      flex: 1,
    },
    displaySwitchChip: {
      backgroundColor: colors.bgSubtle,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 4,
      minHeight: 28,
      justifyContent: "center",
    },
    displaySwitchChipActive: {
      backgroundColor: colors.btnPrimaryBg,
      borderColor: colors.btnPrimaryBg,
    },
    displaySwitchText: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
    displaySwitchTextActive: {
      color: colors.btnPrimaryText,
      fontWeight: "700",
    },
    footerContainer: {
      gap: 14,
      marginTop: 6,
    },
    advancedFooterSection: {
      marginTop: 2,
    },
    itemPressed: {
      opacity: 0.75,
      transform: [{ scale: 0.98 }],
    },

    /* Modals */
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "flex-end",
    },
    modalSheet: {
      backgroundColor: colors.bgCanvas,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      borderWidth: 1,
      borderColor: colors.borderSubtle,
      maxHeight: "88%",
    },
    modalHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderSubtle,
      backgroundColor: colors.bgSurface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: colors.textPrimary,
    },
    modalCloseBtn: {
      padding: 8,
      borderRadius: 8,
      minWidth: 44,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    modalScrollView: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 32,
    },
    modalContentGap: {
      gap: 16,
    },
    modalSection: {
      gap: 8,
    },
    modalSectionTitle: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textSecondary,
    },
  });
}
