[package]
name = "leftcar-rustra"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "leftcar_rustra"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
control-contract = { path = "../../crates/control-contract" }
rustra = { git = "https://github.com/loopy-lim/rustra", rev = "643a1ffad45fc9b1bda29f9d6a9188bab8cc86a0" }
serde_json = { workspace = true }
