[package]
name = "leftcar-rustra"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "leftcar_rustra"
crate-type = ["cdylib", "rlib", "staticlib"]

[dependencies]
control-contract = { path = "../../crates/control-contract" }
rustra = { git = "https://github.com/loopy-lim/rustra", rev = "a9e3ee6b12c031f328e2b6ed93bd667f0085119c" }
serde_json = { workspace = true }
