[package]
name = "android-viewer"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "leftcar_viewer"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
viewer-core = { path = "../../crates/viewer-core" }
viewer-decoder = { path = "../../crates/viewer-decoder" }
domain = { path = "../../crates/domain" }
libc = "0.2"
