import { colors, hitTargets, radii, typography } from "./tokens";

function argb(value: string): string {
  if (value.startsWith("#")) return `0xFF${value.slice(1).toUpperCase()}.toInt()`;
  const channels = value.match(/[\d.]+/g)?.map(Number);
  if (!channels || channels.length !== 4) throw new Error(`Unsupported native color ${value}`);
  return `0x${[Math.round(channels[3] * 255), ...channels.slice(0, 3)].map(channel => channel.toString(16).padStart(2, "0")).join("").toUpperCase()}.toInt()`;
}

/** Video chrome has an opaque dark surface in both application themes. */
export function renderStreamUiTokens(): string {
  const palette = colors.dark;
  const roles = { SURFACE: palette.bgSurface, SUBTLE: palette.bgSubtle, INK: palette.textPrimary, MUTED: palette.textMuted, OUTLINE: palette.borderCard };
  return `// Generated by tools/generate-ui-theme.ts from ui-tokens. Do not edit.
package dev.leftcar.viewer.stream

internal object StreamUiTokens {
${Object.entries(roles).map(([role, color]) => `    val ${role}: Int = ${argb(color)}`).join("\n")}
    const val MIN_TARGET_DP = ${hitTargets.mobileMin}
    const val CAPTION_SP = ${typography.fontSize.xs}f
    const val BODY_SP = ${typography.fontSize.base}f
    const val TITLE_SP = ${typography.fontSize.lg}f
    const val RADIUS_DP = ${radii.md}
}
`;
}
