import { colors, typography, radii, spacing, type ThemeTokens } from "./tokens";

const roleKeys = {
  canvas: "bgCanvas", surface: "bgSurface", subtle: "bgSubtle", hover: "bgHover",
  ink: "textPrimary", muted: "textMuted", secondary: "textSecondary",
  outline: "borderCard", strong: "borderStrong", focus: "borderFocus",
  action: "btnPrimaryBg", "action-ink": "btnPrimaryText",
  curtain: "curtain", "curtain-ink": "curtainInk",
  qr: "qr",
  active: "bgActive", scrim: "scrim",
} satisfies Record<string, keyof ThemeTokens>;

function declarations(palette: ThemeTokens, prefix: string): string {
  return Object.entries(roleKeys).map(([role, key]) => `    --${prefix}${role}: ${palette[key]};`).join("\n");
}

function scale(): string {
  const typeRoles = { caption: "xs", label: "sm", body: "base", title: "lg", subtitle: "xl", heading: "xxl", code: "xs" } as const;
  const type = Object.entries(typeRoles).flatMap(([role, key]) => [
    `  --text-${role}: ${typography.fontSize[key]}px;`,
    `  --text-${role}--line-height: ${typography.lineHeight[key]}px;`,
  ]);
  const radius = Object.entries(radii).map(([key, value]) => `  --radius-${key}: ${value}px;`);
  return [...type, ...radius, `  --spacing: ${spacing[1]}px;`].join("\n");
}

/** Both outputs are generated from the same roles. No theme literals in screens. */
export function renderThemeCss(platform: "host" | "viewer"): string {
  const heading = "/* Generated by tools/generate-ui-theme.ts from ui-tokens. Do not edit. */\n";
  if (platform === "viewer") {
    return `${heading}@theme {\n${scale()}\n${declarations(colors.light, "color-")}\n}\n@layer theme {\n  :root {\n    @variant light {\n${declarations(colors.light, "color-")}\n    }\n    @variant dark {\n${declarations(colors.dark, "color-")}\n    }\n  }\n}\n`;
  }
  const aliases = Object.keys(roleKeys).map((role) => `  --color-${role}: var(--ui-${role});`).join("\n");
  return `${heading}@theme {\n${scale()}\n}\n@theme inline {\n${aliases}\n}\n:root {\n${declarations(colors.light, "ui-")}\n}\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n${declarations(colors.dark, "ui-")}\n  }\n}\n:root[data-theme=\"dark\"] {\n${declarations(colors.dark, "ui-")}\n}\n`;
}
