export interface SessionRow {
  session: number;
  sourceIndex: number;
  sourceName: string;
  viewerAddr: string;
  state: string;
  fps: number;
  kbps: number;
  fpsTarget?: number;
  captureFps?: number;
  encodeSubmitFps?: number;
  encodeOutputFps?: number;
  renderedFps?: number | null;
  captureCallbacks?: number;
  encodeOutputCallbacks?: number;
  encodeSubmitFailures?: number;
  encodeInFlight?: number;
  inputEnabled: boolean;
  inputRateHz: number;
  dropped?: number;
  networkDropped?: number;
  networkQueueDropped?: number;
  recoveryFramesDropped?: number;
  recoveryKeyframes?: number;
  recoveryRequestsSuppressed?: number;
  udpSendFailures?: number;
  captureQueueDropped?: number;
  captureToEncodeUs?: number;
  maxCaptureToEncodeUs?: number;
  captureQueueWaitUs?: number;
  maxCaptureQueueWaitUs?: number;
  encodeOutputUs?: number;
  maxEncodeOutputUs?: number;
  packetizationUs?: number;
  maxPacketizationUs?: number;
  sendBlockUs?: number;
  maxSendBlockUs?: number;
  pendingFrame?: number;
  pendingFrameBytes?: number;
  pendingFrameOldestAgeUs?: number;
  frames?: number;
  bytes?: number;
  captureBackend?: string;
  mediaTransport?: string;
  firstCaptureMs?: number;
  firstEncodeMs?: number;
  firstSendMs?: number;
  currentBitrate?: number;
  qualityHint?: number | null;
  qualityOverride?: number | null;
  qualityAdaptationChecks?: number;
  qualityAdaptationChanges?: number;
  qualityAdaptationRejections?: number;
  qualityAdaptationLastStatus?: string;
  encoderMode?: "ave" | "rtvc" | "unknown" | string;
  encoderID?: string;
  encoderHardwareAccelerated?: boolean | null;
  encoderPreset?: string;
  encoderProfile?: string;
  encoderAppliedProperties?: string[];
  encoderUnsupportedProperties?: string[];
  encoderRejectedProperties?: string[];
  encoderFallbackReason?: string | null;
  captureIntervalP95Us?: number;
  captureToEncodeP95Us?: number;
  captureQueueWaitP95Us?: number;
  encodeOutputP95Us?: number;
  packetizationP95Us?: number;
  encodeOutputIntervalP95Us?: number;
  sendBlockP95Us?: number;
  sendPaceP95Us?: number;
  lastAuBytes?: number;
  lastAuFragments?: number;
  lastAuParity?: number;
  lastAuDatagrams?: number;
  lastAuExpectedDatagrams?: number;
  lastAuSendUs?: number;
  lastAuIsKeyframe?: boolean;
  maxAuBytes?: number;
  maxAuFragments?: number;
  sentDatagrams?: number;
  sentParityDatagrams?: number;
  receiverFrameGaps?: number;
  receiverInputDrops?: number;
  receiverIncompleteAus?: number;
  receiverStaleFrames?: number;
  receiverOutputBurstDiscards?: number;
  receiverRttMs?: number | null;
  receiverWireMs?: number | null;
  receiverFeedbackAgeMs?: number | null;
  error?: string | null;
}
