// Generated by tools/generate-ui-theme.ts from ui-tokens. Do not edit.
package dev.leftcar.viewer.stream

internal object StreamUiTokens {
    val SURFACE: Int = 0xFF18181B.toInt()
    val SUBTLE: Int = 0xFF27272A.toInt()
    val INK: Int = 0xFFFAFAFA.toInt()
    val MUTED: Int = 0xFFA1A1AA.toInt()
    val OUTLINE: Int = 0x24FFFFFF.toInt()
    const val MIN_TARGET_DP = 44
    const val CAPTION_SP = 12f
    const val BODY_SP = 15f
    const val TITLE_SP = 18f
    const val RADIUS_DP = 10
}
