[package]
name = "transport-api"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }
domain = { workspace = true }
media-model = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
network-protocol = { workspace = true }
serde_json = { workspace = true }
