[package]
name = "transport-quic"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
bytes = { workspace = true }
domain = { workspace = true }
media-model = { workspace = true }
transport-api = { workspace = true }
